### ISSUE TITLE
Optional short names

### ISSUE THREAD

**Issue by j-maly** [j-maly/CommandLineParser#10]
Short names are mandatory for all arguments. This can be difficult for applications with many recognized arguments.

**Comment by wleader** [comment]
I wanted to use this library because I need to parse the command line based on data that is not known at compile time. Almost all the other parsers I looked at are declarative meaning I would have to create classes and decorate them which won't work for me. This library could have worked except that I have no good way to get a single unique character for each command at run time.

**Comment by StefH** [comment]
By default you can take the first character for the commands. And if there are duplicates, just take the second and so on.

**Comment by j-maly** [comment]
Should work in 3.0.6
